version: '3.8'

services:
  sybil:
    container_name: sybil
    build:
      context: ./io.exonym.rulebook
      dockerfile: Dockerfile
    image: rulebook:latest
    environment:
     - HTTPS_METHOD=noredirect
     - VIRTUAL_HOST=localhost
     - VIRTUAL_PORT=9084
    ports: 
      - 8080:8080
    env_file:
        - io.exonym.rulebook/conf/e-vanilla-s.env
    volumes:
      - ~/github/rulebook-node/io.exonym.rulebook/static:/var/www/html/static
    networks:
      - rulebook_network

  rulebook-node:
    container_name: rulebook-node
    build:
      context: ./io.exonym.rulebook
      dockerfile: Dockerfile
    image: rulebook:latest
    environment:
      - HTTPS_METHOD=noredirect
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=9084
    ports:
      - 8081:8080
    env_file:
      - io.exonym.rulebook/conf/e-vanilla-sx.env
    volumes:
      - ~/github/rulebook-node/io.exonym.rulebook/static1:/var/www/html/static
    networks:
      - rulebook_network


  couchdb:
    container_name: couchdb
    image: couchdb:3
    environment:
      - COUCHDB_USER=${DB_USERNAME}
      - COUCHDB_PASSWORD=${DB_PASSWORD}
    ports:
      - 5984:5984
    volumes:
      - ~/github/rulebook-node/io.exonym.rulebook/couchdb/data:/opt/couchdb/data
    networks:
      - rulebook_network

networks:
 rulebook_network:
  name: rulebook_network
